# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: VSS-30 Simulator Emulator
email: fluworks@gmail.com
description: >
  FL Microworks Effects is on a quest to build high quality electronic and audio effects
  devices.  The VSS-30 project will use an AVR 8-bit MCU to emulate the sampler
  found on a Yamaha VSS-30.  Why?  ...Why not?
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "fluworks.github.io/VSS-30" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: FLuworks
github_username:  FLuworks

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
